name: Docker Kubernetes MultiDocker Deployment Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build and tag Docker images
        run: |
          docker build -t ibnumahamat/multi-client:latest ./client
          docker build -t ibnumahamat/multi-nginx:latest ./nginx
          docker build -t ibnumahamat/multi-server:latest ./server
          docker build -t ibnumahamat/multi-worker:latest ./worker

          # Also tag with Git SHA for traceability
          docker tag ibnumahamat/multi-client:latest ibnumahamat/multi-client:${{ github.sha }}
          docker tag ibnumahamat/multi-nginx:latest ibnumahamat/multi-nginx:${{ github.sha }}
          docker tag ibnumahamat/multi-server:latest ibnumahamat/multi-server:${{ github.sha }}
          docker tag ibnumahamat/multi-worker:latest ibnumahamat/multi-worker:${{ github.sha }}

      - name: Push Docker images to Docker Hub
        run: |
          docker push ibnumahamat/multi-client:latest
          docker push ibnumahamat/multi-client:${{ github.sha }}

          docker push ibnumahamat/multi-nginx:latest
          docker push ibnumahamat/multi-nginx:${{ github.sha }}

          docker push ibnumahamat/multi-server:latest
          docker push ibnumahamat/multi-server:${{ github.sha }}

          docker push ibnumahamat/multi-worker:latest
          docker push ibnumahamat/multi-worker:${{ github.sha }}

      - name: Generate deployment package
        run: zip -r deploy.zip . -x '*.git*'

      - name: Deploy to AWS Elastic Beanstalk
        uses: einaregilsson/beanstalk-deploy@v21
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY }}
          AWS_REGION: eu-north-1
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
          application_name: multi-docker
          environment_name: Multi-docker-env
          existing_bucket_name: elasticbeanstalk-eu-north-1-439446323892
          region: eu-north-1
          version_label: ${{ github.sha }}
          deployment_package: deploy.zip
