name: Docker-Kubernetes Test Workflow

on:
  pull_request:
        branches: 
            - dev
        paths:
            - './client/**'

jobs:
    test:
        runs-on: ubuntu-latest
        name: Test React Client
        steps:
          - name: Checkout code
            uses: actions/checkout@v4
          - name: Docker login
            run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
          - name: Build Docker image
            run: docker build -t ibnumahamat/react-client-test -f ./client/Dockerfile.dev ./client
          - name: Run tests
            run: docker run -e CI=true ibnumahamat/react-client-test npm test
