name: Docker-Kubernetes Test Workflow

on:
    pull_request:
        branches: 
            - dev
        paths:
            - './client/**'

jobs:
    test:
        runs-on: ubuntu-latest

        steps:
          - name: Checkout code
            uses: actions/checkout@v4
          - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          - run: docker build -t ibnumahamat/react-client-test t -f ./client/Dockerfile.dev ./client
          - run: docker run -e CI=true ibnumahamat/react-client-test npm test